### ISSUE TITLE
not building after deleting template blog post

### ISSUE THREAD

**Issue by fpigeonjr** [maxpou/gatsby-starter-morning-dew#36]
❤️ Love this template and am using it for [my personal blog](https://frankpigeon.com).

I found an issue with the gatsby build failing after I deleted the template blog post entitled `gatsby-starter-morning-dew-v1-1`. 

I was able to delete the other ones with no issue.

👍Thanks for your support!

**Comment by maxpou** [comment]
Hey @fpigeonjr ,
Thanks for the feedback. I'm glad to see other people using this template 😃 

What is the error message in your console?

**Comment by fpigeonjr** [comment]
sorry for the delay @maxpou 

![Imgur](https://i.imgur.com/rLzRfsx.png)

## steps to recreate
1. create gatsby site w/ template
1. `yarn develop`
1. delete all the posts
1. create a new post
1.  error

```bash

~/Code/deletmeBlog   100s
❯ yarn dev
yarn run v1.12.3
$ gatsby develop
success open and validate gatsby-configs — 0.014 s
success load plugins — 0.223 s
success onPreInit — 0.439 s
success delete html and css files from previous builds — 0.079 s
success initialize cache — 0.009 s
success copy gatsby files — 0.076 s
success onPreBootstrap — 0.004 s
success source and transform nodes — 0.075 s
success building schema — 0.237 s
⠁ [ { GraphQLError: Cannot query field "tags" on type "frontmatter".
      at Object.Field (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
      at Object.enter (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/language/visitor.js:324:29)
      at Object.enter (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/language/visitor.js:366:25)
      at visit (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/language/visitor.js:254:26)
      at visitUsingRules (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/validation/validate.js:74:22)
      at validate (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/validation/validate.js:59:10)
      at graphqlImpl (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/graphql.js:106:50)
      at /Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/graphql.js:66:223
      at Promise._execute (/Users/fpigeonjr/Code/deletmeBlog/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (/Users/fpigeonjr/Code/deletmeBlog/node_modules/bluebird/js/release/promise.js:483:18)
      at new Promise (/Users/fpigeonjr/Code/deletmeBlog/node_modules/bluebird/js/release/promise.js:79:10)
      at graphql (/Users/fpigeonjr/Code/deletmeBlog/node_modules/graphql/graphql.js:63:10)
      at graphqlRunner (/Users/fpigeonjr/Code/deletmeBlog/node_modules/gatsby/dist/bootstrap/index.js:372:14)
      at Object.exports.createPages (/Users/fpigeonjr/Code/deletmeBlog/gatsby-node.js:14:29)
      at runAPI (/Users/fpigeonjr/Code/deletmeBlog/node_modules/gatsby/dist/utils/api-runner-node.js:154:37)
      at resolve (/Users/fpigeonjr/Code/deletmeBlog/node_modules/gatsby/dist/utils/api-runner-node.js:258:19)
    message: 'Cannot query field "tags" on type "frontmatter".',
    locations: [ { line: 10, column: 17 } ],
    path: undefined } ]
error gatsby-node.js returned an error


  Error: Cannot query field "tags" on type "frontmatter".
  GraphQL request (10:17)
   9:                 type
  10:                 tags
                      ^
  11:               }

  - gatsby-node.js:35 Object.exports.createPages
    /Users/fpigeonjr/Code/deletmeBlog/gatsby-node.js:35:11


success createPages — 0.031 s
success createPagesStatefully — 0.027 s
success onPreExtractQueries — 0.011 s
success update schema — 0.164 s
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
Site.siteMetadata.footerLinks[]:
 - type: array<object|string>
   value: [ 'Explore', { label: 'Blog', url: '/' }, ... ]
warning Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
/Users/fpigeonjr/Code/deletmeBlog/src/pages/404.js
error GraphQL Error Field "tags" is not defined by type markdownRemarkConnectionFrontmatterInputObject_2.

  file: /Users/fpigeonjr/Code/deletmeBlog/src/templates/tags.js

   1 |
   2 |   query PostsByTag($tag: String!) {
   3 |     allMarkdownRemark(
   4 |       sort: { fields: [frontmatter___date], order: DESC }
>  5 |       filter: { frontmatter: { tags: { eq: $tag } } }
     |                                ^
   6 |     ) {
   7 |       edges {
   8 |         node {
   9 |           excerpt
  10 |           frontmatter {
  11 |             date(formatString: "DD MMMM, YYYY")
  12 |             title
  13 |             tags
  14 |             language
  15 |             slug

success extract queries from components — 0.101 s
⠁ (node:50947) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.
success run graphql queries — 0.020 s — 3/3 190.51 queries/second
success write out page data — 0.014 s
success write out redirect data — 0.002 s
⡀ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.207 s

info bootstrap finished - 3.336 s

 DONE  Compiled successfully in 1257ms                                                                                                                                                           3:14:25 PM


You can now view gatsby-starter-morning-dew in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use gatsby build

ℹ ｢wdm｣:
ℹ ｢wdm｣: Compiled successfully.

```

**Comment by maxpou** [comment]
Hey @fpigeonjr,
I've found the issue: 3 mandatory fields were missing in your markdown files:
* `language`: allow to write post in different languages (default `en`)
* `imageTw`: allow meta images for social medias (see: https://maxpou.github.io/gatsby-starter-morning-dew/gatsby-starter-morning-dew-v1-1#-social-media-card-generator)
* `imageFb`: same as `imageTw`

In GraphQL, as far I know, you can't set default values on non existing fields. If the field doesn't exist, an error is thrown. It was basically your problem.

I opened a [PR](https://github.com/fpigeonjr/myBlog/pull/2/files#diff-d3f66e293fceee3578de1269acac8a76) in your repo.

```markdown
language: en
cover: ./code.jpg
# actual cover
imageTw: ./code.jpg
imageFb: ./code.jpg
```

You don't need to update all of your posts!
 I hope your problem is fixed now :)

**Comment by fpigeonjr** [comment]
wow @maxpou, thank you so much. No one has ever sent me a PR and it is humbling to know that people are so giving of their time.

I confirmed the PR worked and the default blog post is removed.
I also learned that each blog post has required fields. I'll make sure and add them to the other blog posts that I have created.

🎅Thanks again for helping me and Merry Christmas!
